# Generated by Django 2.2.5 on 2019-09-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address_line_1', models.CharField(max_length=50)),
                ('address_line_2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=300)),
                ('opening_times_mon', models.CharField(max_length=50)),
                ('opening_times_tue', models.CharField(max_length=50)),
                ('opening_times_wed', models.CharField(max_length=50)),
                ('opening_times_thur', models.CharField(max_length=50)),
                ('opening_times_fri', models.CharField(max_length=50)),
                ('opening_times_sat', models.CharField(max_length=50)),
                ('opening_times_sun', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
