# Generated by Django 2.2.5 on 2019-09-05 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address_line_1', models.CharField(max_length=50)),
                ('address_line_2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('opening_times_mon', models.CharField(max_length=50)),
                ('opening_times_tue', models.CharField(max_length=50)),
                ('opening_times_wed', models.CharField(max_length=50)),
                ('opening_times_thur', models.CharField(max_length=50)),
                ('opening_times_fri', models.CharField(max_length=50)),
                ('opening_times_sat', models.CharField(max_length=50)),
                ('opening_times_sun', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('comments', models.ManyToManyField(blank=True, related_name='workspace', to='workspaces.Comment')),
                ('genres', models.ManyToManyField(blank=True, related_name='workspace', to='workspaces.Genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
