# Generated by Django 2.2.5 on 2019-09-05 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='workspaces', to='workspaces.Comment'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='workspaces', to='workspaces.Genre'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
