# Generated by Django 2.2.5 on 2019-09-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_auto_20190905_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
