# Generated by Django 2.2.5 on 2019-09-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_auto_20190904_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='category',
            new_name='categorys',
        ),
    ]
