# Generated by Django 2.2.5 on 2019-09-10 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0004_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='workspaces_bo', to=settings.AUTH_USER_MODEL),
        ),
    ]
