# Generated by Django 2.2.5 on 2019-09-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_auto_20190907_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='website',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
