# Generated by Django 2.2.5 on 2019-09-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_workspace_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='website',
            new_name='link',
        ),
    ]
