# Generated by Django 2.2.5 on 2019-09-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_auto_20190909_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
