# Generated by Django 2.2.5 on 2019-09-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_auto_20190906_1017'),
        ('jwt_auth', '0003_user_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='workspace',
        ),
        migrations.AddField(
            model_name='user',
            name='userworkspaces',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='workspaces.Workspace'),
            preserve_default=False,
        ),
    ]
