# Generated by Django 2.2.5 on 2019-09-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_auto_20190906_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userworkspaces',
        ),
    ]
